### PR TITLE
Bump Rocket.Chat 3.2.1

### PR DESCRIPTION
**Pull request by aminvakil**

### CODE REVIEW

**Comment by tobiasreinhard** [comment]
any news on this?

**Comment by aminvakil** [comment]
As 3.1.3 is out too, I don't know if this should change to 3.1.3 or 3.2.1 is still the latest release?

**Comment by sampaiodiego** [comment]
thanks @aminvakil .. I'll merge this.. but before publishing I'll update to 3.2.2, that is underway already.. thanks again and sorry the delay

**Comment by aminvakil** [comment]
https://github.com/docker-library/official-images/pull/7992

**Pull request merged**
