### PR TITLE
Uses debian image as base

### PR DESCRIPTION
**Pull request by pierreozoux**
@engelgabriel @Sing-Li 

I did as we discussed. (I removed some debugging things and one layer)
What do you think?

If you agree, then, I'll ping docker maintainer to be sure.

### CODE REVIEW

**Comment by Sing-Li** [comment]
LGTM

I've checked out the branch and built the image.  Worked okay.  :+1:

**Comment by pierreozoux** [comment]
@tianon just to let you know, we updated the base image to not use node:0.10 any more, for security matters.

Let us know if you have any problems with it?

**Comment by tianon** [comment]
I'm not sure I entirely understand the purpose of duplicating the maintainership effort of the `node` team here (given that `node:0.10` is still officially supported, and will receive security updates as appropriate, as was noted in https://github.com/docker-library/official-images/issues/1764).

**Comment by Sing-Li** [comment]
Interesting.   Did not realize it is still actively maintained. 

@pierreozoux @engelgabriel  - what do you think?  Should we just wait and revert back to `node:0.10`.   

As @tianon pointed out, this will greatly reduce our maintenance-surface :)

**Comment by pierreozoux** [comment]
@engelgabriel also said that this way the image is lighter.

I thought the image was not maintained any more, that's why the rework.
If it is still maintained, I'd go for keeping node.

At the end of the day, the decision is on your side @Sing-Li @engelgabriel

**Comment by mide** [comment]
I'd be curious how much lighter the new image is; does it really warrant duplicated effort? It's a whole bunch to keep in sync and maintain.

Either way, just my two cents.

**Comment by tianon** [comment]
If the new image is lighter, I'd recommend looking at "node:0.10-slim"
(which should be a very similar size footprint).

**Comment by engelgabriel** [comment]
Indeed node:0.10-slim was the inspiration for our changes:
https://github.com/nodejs/docker-node/blob/5e058d36cc69303d1f62d424615fa03e050f20ef/0.10/slim/Dockerfile
So maybe we should use it instead. What do you think @pierreozoux ?

**Comment by pierreozoux** [comment]
Sorry, I didn't have time :/

I think we should use `node:0.10-slim` but I don't have the time to PR :/

**Pull request merged**
