### PR TITLE
Add missing fontconfig package

### PR DESCRIPTION
**Pull request by j-stahl**
Rocket.Chat server generates for the mobil devices avatar icons with letters, when the users did not upload pictures. For generating this avatars the app need fonts, which weren't included yet in the Rocket.Chat docker image.
Issue: https://github.com/RocketChat/Rocket.Chat.iOS/issues/2393

### CODE REVIEW

**Comment by aimbot31** [comment]
Up

**Comment by sampaiodiego** [comment]
Thanks guys. Sorry the delay.. this change will be available in the 2.3.1 release.

**Comment by aimbot31** [comment]
> Thanks guys. Sorry the delay.. this change will be available in the 2.3.1 release.

Hi, do you know when the version 2.3.1 will be published in the docker hub ?

**Comment by sampaiodiego** [comment]
you can track this PR https://github.com/docker-library/official-images/pull/7099

once that is merged, just need to wait the automated process to be publish the image

**Pull request merged**
