### PR TITLE
Update "gpg" invocations to use "--batch"

### PR DESCRIPTION
**Pull request by tianon**
See https://bugs.debian.org/913614

### CODE REVIEW

**Comment by lag-linaro** [comment]
I was about to submit this myself.

LGTM.

**Comment by lag-linaro** [comment]
@tianon looks like you have to sign the agreement to contribute.

**Comment by tianon** [comment]
That seems kind of silly given that I already have merge access and previous commits.  I'm a bit concerned about the maintenance of this image, to be honest (doesn't seem to be a whole lot of activity on this repository besides the bot doing version bumps).

**Comment by lag-linaro** [comment]
Maybe @pierreozoux, @sampaiodiego or @geekgonecrazy can shed some light?

**Review by pierreozoux — APPROVED** [review]

**Comment by pierreozoux** [comment]
@lag-linaro see https://github.com/RocketChat/Docker.Official.Image/issues/61

**Comment by lag-linaro** [comment]
> @lag-linaro see #61

I see it.  Is there anything you want me to action?  Or just be aware of it?

Will someone review my PR too? #60

**Pull request merged**
