### PR TITLE
Revert #20 (7d819cdc7cbc4fced21d28ef2926883a10b88d11) and switch to "node:0.10-slim" instead

### PR DESCRIPTION
**Pull request by tianon**
As discussed in https://github.com/RocketChat/Docker.Official.Image/pull/20#issuecomment-222171055

### CODE REVIEW

**Comment by tianon** [comment]
Here's the full diff from before that PR, for reference:
```diff
--- Dockerfile	2016-06-07 09:09:26.911086874 -0700
+++ /dev/fd/63	2016-06-07 09:09:28.019055714 -0700
@@ -1,4 +1,4 @@
-FROM node:0.10-slim
+FROM node:0.10
 
 # crafted and tuned by pierre@ozoux.net and sing.li@rocket.chat
 MAINTAINER buildmaster@rocket.chat
```

**Comment by pierreozoux** [comment]
Ok, looks good to me!

**Comment by tianon** [comment]
@engelgabriel @Sing-Li either of you want to give this a look/your thoughts before we merge it? :smile:

**Comment by Sing-Li** [comment]
LGTM :+1:

Tianon - please allow us to pick your brain.  

You were one of those super earlier pioneers in Docker to champion slim images - ultra reduced sized images via side-loading and other interesting techniques.  Is the technique really STILL relevant given that most deployment environment uses distributed local repositories and only differences in layers get transmitted on-the-wire in most cases?   Any thoughts appreciated.

**Comment by tianon** [comment]
Heh, I think both slim and fat images have their use cases -- we still actively maintain and support all the variants of `buildpack-deps`, even though the _primary_ purpose of the image is "massive bloat".

For some folks, transfer rates and storage size are huge constraints (especially when talking with my friends in Australia who complain constantly about the abysmal state of DSL and home internet connections there), but for others, it's more important to share a large base, or to ensure that the time spent "figuring out which dependency our application needs" is a minimum (which is where `buildpack-deps` sits -- include the entire sink such that only really rare edge-cases require additional dependencies).

**Pull request merged**
