### PR TITLE
update Docker's "MAINTAINER" instruction

### LINKED ISSUE #41: Use alpine versions of node
The official node images are also available as "alpine" versions - please consider using these as base images which would reduce the image size a lot.

### LINKED ISSUE #69: Docker "MAINTAINER" instruction is deprecated
Docker deprecated the "MAINTAINER " instruction in favor of "LABEL maintainer ". 

See:- https://docs.docker.com/engine/reference/builder/#maintainer-deprecated

I will make a PR for the same

### PR DESCRIPTION
**Pull request by knrt10**
This PR  updates Docker's "MAINTAINER" instruction as it is deprecated.

Fixes #69

cc @Sing-Li would you please review.

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
You can’t simply switch to the alpine base.  When you start it things like sharp will break.

**Comment by knrt10** [comment]
So should I change it back, and just let the MAINTAINER be updated?

cc @geekgonecrazy

**Comment by knrt10** [comment]
@geekgonecrazy updated the PR, please review

**Comment by geekgonecrazy** [comment]
> Although docker image was running fine.

Please see the alpine PR in our main repo for an example of the trickery required :)

Will take a look at update!

**Comment by geekgonecrazy** [comment]
Thanks for the contribution

**Pull request merged**
