### PR TITLE
Update to 0.15.0

### PR DESCRIPTION
**Pull request by jasperla**

### CODE REVIEW

**Comment by tianon** [comment]
LGTM cc @engelgabriel @pierreozoux

**Comment by jasperla** [comment]
Thanks. Is there anything further required from my side to get this synced to docker-library/official-images or is there an existing workflow from your side?

**Comment by sarahactisdano** [comment]
[Dockerfile.txt](https://github.com/RocketChat/Docker.Official.Image/files/12642682/Dockerfile.txt)

**Comment by sarahactisdano** [comment]
```dockerfile

```

**Pull request merged**
