### PR TITLE
Bump Rocket.Chat 3.5.0

### PR DESCRIPTION
**Pull request by sandrotanner**
https://github.com/RocketChat/Rocket.Chat/releases/tag/3.5.0

### CODE REVIEW

**Comment by aminvakil** [comment]
https://github.com/RocketChat/Docker.Official.Image/issues/112#issuecomment-629438594

> https://hub.docker.com/_/rocket-chat is a release approved by docker team too, therefore it will be always older (from my experience about two weeks) than the rocketchat official one.


As I thought official rocketchat which is approved by docker team too is at least tested two weeks prior to be in docker hub, I have enabled automatic image update on all of my rocketchat servers, has this been changed?

This new version is only 1 day old, although there has been several rcs prior to releasing the rocketchat stable version.

Is there a fixed delay for upgrading rocketchat docker image after rocketchat gets upgraded itself?

**Comment by sampaiodiego** [comment]
there is no official delay in between a rocket.chat release is cut and the official docker image is published.. we're actually trying to release both as close as possible.

**Comment by sandrotanner** [comment]
@aminvakil If you want automatic updates but lack behind by two weeks you could probably create a script to checkout the latest commit that is more than two weeks old and build the image.

`git log --before 14.days.ago -1`

**Comment by aminvakil** [comment]
@sampaiodiego Thanks for the clarification.

@sandrotanner Thanks for your suggestion, but I'm not building docker image from git repo, but using the image https://hub.docker.com/_/rocket-chat.

**Comment by sandrotanner** [comment]
@aminvakil  I know. My suggestion was that you change that if you want to withhold the latest stable version for two weeks on your servers :) The resulting image is exactly the same as using docker-compose pull but you have the control over when you deploy a new version (which seems like what you want).

**Pull request merged**
