### PR TITLE
Bump version to 0.44.0

### PR DESCRIPTION
**Pull request by geekgonecrazy**
#26 should be merged first.

### CODE REVIEW

**Comment by pierreozoux** [comment]
Arf sorry that this is left behind, but @tianon has a script for it.

Can you run it please?

**Comment by tianon** [comment]
@pierreozoux can you add @docker-library-bot to the list of collaborators? :pray:

**Comment by pierreozoux** [comment]
@engelgabriel or @Sing-Li can make that happen I'm sure :)

**Comment by geekgonecrazy** [comment]
@pierreozoux / @tianon added

**Pull request merged**
